### ISSUE TITLE
Assertion failed: refresh, file socket_utils.c, line 167

### ISSUE THREAD

**Issue by floxay** [Morilli/ManifestDownloader#1]
Hey, when I try to use the tool on VALORANT manifest files I get this error:
```
Downloading file Engine/Binaries/ThirdParty/CEF3/Win64/Resources/cef.pak...
Assertion failed: refresh, file socket_utils.c, line 167
```

**Comment by Morilli** [comment]
Hm, I have encountered this issue before... from what I believe to be happening, it's the server returning something unexpected and therefore my program fails unexpectedly. Can you provide me the manifest url you tested this with? (and if possible, the arguments too)

**Comment by floxay** [comment]
Oops, forgot to change the bundle url, my bad!

Edit: Thank you for this tool :)

**Comment by Morilli** [comment]
I've managed to reproduce this issue, and I know why it happens and how to fix it. Will re-open until I push my fix.
