### ISSUE TITLE
Can't run the exe file

### ISSUE THREAD

**Issue by Dafner1** [Morilli/ManifestDownloader#5]
Hi,

Whenever I try to run the exe file, it does not open. It just does nothing.

**Comment by Morilli** [comment]
You'll need to run the program in a command line, like powershell. 

Easiest way on windows is to (shift) rightclick the background in the explorer window and select "open powershell here" (or whatever it's called).

**Comment by Dafner1** [comment]
Whenever I try to run it in command line, it still does not open.

I am using the powershell with the start command.

**Comment by Morilli** [comment]
Don't use the start command

**Comment by Dafner1** [comment]
thanks, it works <3

Sorry for my noob questions
