### ISSUE TITLE
Valorant Error: Got a 404 response.

### ISSUE THREAD

**Issue by L0caler** [Morilli/ManifestDownloader#7]
I get this error with multiple Valorant Manifests. For League it works.

```
Downloading file Engine/Binaries/ThirdParty/CEF3/Win64/Resources/cef.pak...
Error: Got a 404 response.
Failed to download. Make sure to use the correct bundle base url (if necessary).
```

**Comment by Morilli** [comment]
Are you providing the correct bundle base path in the command line? The default value works fine for league, but not for other games.

For example for valorant, you should be using `-b https://valorant.secure.dyn.riotcdn.net/channels/public/bundles` in addition to other arguments.

**Comment by L0caler** [comment]
thanks
